# -*- coding: utf-8 -*-

class KyuubiState(object):

    KYUUBI_INITIALIZED = 'INITIALIZED'
    KYUUBI_PENDING = 'PENDING'
    KYUUBI_RUNNING = 'RUNNING'
    KYUUBI_COMPILED = 'COMPILED'
    KYUUBI_FINISHED = 'FINISHED'
    KYUUBI_TIMEOUT = 'TIMEOUT'
    KYUUBI_CANCELED = 'CANCELED'
    KYUUBI_CLOSED = 'CLOSED'
    KYUUBI_ERROR = 'ERROR'
    KYUUBI_UNKNOWN = 'UNKNOWN'

    success_state = [KYUUBI_FINISHED]

    failed_state = [KYUUBI_CANCELED, KYUUBI_CLOSED, KYUUBI_ERROR]

    running_state = [KYUUBI_COMPILED, KYUUBI_RUNNING]

    finish_state = [KYUUBI_FINISHED,KYUUBI_CANCELED, KYUUBI_CLOSED, KYUUBI_ERROR]