# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TaskServiceApi.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from entity import ScheduleJob_pb2 as entity_dot_ScheduleJob__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='TaskServiceApi.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\027com.ushareit.dstask.apiB\016TaskServiceApi',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14TaskServiceApi.proto\x1a\x18\x65ntity/ScheduleJob.proto\"2\n\tIDRequest\x12%\n\ridVersionPair\x18\x01 \x03(\x0b\x32\x0e.IdVersionPair\"\x1f\n\x0bNameRequest\x12\x10\n\x08taskName\x18\x01 \x01(\t\"B\n\x08Response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x17\n\x04info\x18\x03 \x01(\x0b\x32\t.TaskInfo\"F\n\x0cTaskResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x17\n\x04info\x18\x03 \x03(\x0b\x32\t.TaskInfo\"A\n\rIdVersionPair\x12\x0e\n\x06taskID\x18\x01 \x01(\x05\x12\x14\n\x07version\x18\x02 \x01(\x05H\x00\x88\x01\x01\x42\n\n\x08_version\"\xbf\x01\n\x08TaskInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0bisSparkTask\x18\x02 \x01(\x08\x12\x14\n\x0ctemplateCode\x18\x03 \x01(\t\x12\x15\n\rruntimeConfig\x18\x04 \x01(\t\x12\x12\n\nupdateTime\x18\x05 \x01(\x03\x12\r\n\x05owner\x18\x06 \x01(\t\x12\"\n\x0c\x65ventDepends\x18\x07 \x03(\x0b\x32\x0c.EventDepend\x12\x0c\n\x04name\x18\x08 \x01(\t\x12\x10\n\x08isDelete\x18\t \x01(\x08\x32p\n\x0eTaskRpcService\x12.\n\x11getTaskInfoByName\x12\x0c.NameRequest\x1a\t.Response\"\x00\x12.\n\x0fgetTaskInfoByID\x12\n.IDRequest\x1a\r.TaskResponse\"\x00\x42)\n\x17\x63om.ushareit.dstask.apiB\x0eTaskServiceApib\x06proto3'
  ,
  dependencies=[entity_dot_ScheduleJob__pb2.DESCRIPTOR,])




_IDREQUEST = _descriptor.Descriptor(
  name='IDRequest',
  full_name='IDRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='idVersionPair', full_name='IDRequest.idVersionPair', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=100,
)


_NAMEREQUEST = _descriptor.Descriptor(
  name='NameRequest',
  full_name='NameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='taskName', full_name='NameRequest.taskName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=133,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='Response.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='Response.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='info', full_name='Response.info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=201,
)


_TASKRESPONSE = _descriptor.Descriptor(
  name='TaskResponse',
  full_name='TaskResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='TaskResponse.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='TaskResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='info', full_name='TaskResponse.info', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=273,
)


_IDVERSIONPAIR = _descriptor.Descriptor(
  name='IdVersionPair',
  full_name='IdVersionPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='taskID', full_name='IdVersionPair.taskID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='IdVersionPair.version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_version', full_name='IdVersionPair._version',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=275,
  serialized_end=340,
)


_TASKINFO = _descriptor.Descriptor(
  name='TaskInfo',
  full_name='TaskInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='TaskInfo.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isSparkTask', full_name='TaskInfo.isSparkTask', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='templateCode', full_name='TaskInfo.templateCode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='runtimeConfig', full_name='TaskInfo.runtimeConfig', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='updateTime', full_name='TaskInfo.updateTime', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='owner', full_name='TaskInfo.owner', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eventDepends', full_name='TaskInfo.eventDepends', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='TaskInfo.name', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isDelete', full_name='TaskInfo.isDelete', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=534,
)

_IDREQUEST.fields_by_name['idVersionPair'].message_type = _IDVERSIONPAIR
_RESPONSE.fields_by_name['info'].message_type = _TASKINFO
_TASKRESPONSE.fields_by_name['info'].message_type = _TASKINFO
_IDVERSIONPAIR.oneofs_by_name['_version'].fields.append(
  _IDVERSIONPAIR.fields_by_name['version'])
_IDVERSIONPAIR.fields_by_name['version'].containing_oneof = _IDVERSIONPAIR.oneofs_by_name['_version']
_TASKINFO.fields_by_name['eventDepends'].message_type = entity_dot_ScheduleJob__pb2._EVENTDEPEND
DESCRIPTOR.message_types_by_name['IDRequest'] = _IDREQUEST
DESCRIPTOR.message_types_by_name['NameRequest'] = _NAMEREQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['TaskResponse'] = _TASKRESPONSE
DESCRIPTOR.message_types_by_name['IdVersionPair'] = _IDVERSIONPAIR
DESCRIPTOR.message_types_by_name['TaskInfo'] = _TASKINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IDRequest = _reflection.GeneratedProtocolMessageType('IDRequest', (_message.Message,), {
  'DESCRIPTOR' : _IDREQUEST,
  '__module__' : 'TaskServiceApi_pb2'
  # @@protoc_insertion_point(class_scope:IDRequest)
  })
_sym_db.RegisterMessage(IDRequest)

NameRequest = _reflection.GeneratedProtocolMessageType('NameRequest', (_message.Message,), {
  'DESCRIPTOR' : _NAMEREQUEST,
  '__module__' : 'TaskServiceApi_pb2'
  # @@protoc_insertion_point(class_scope:NameRequest)
  })
_sym_db.RegisterMessage(NameRequest)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'TaskServiceApi_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

TaskResponse = _reflection.GeneratedProtocolMessageType('TaskResponse', (_message.Message,), {
  'DESCRIPTOR' : _TASKRESPONSE,
  '__module__' : 'TaskServiceApi_pb2'
  # @@protoc_insertion_point(class_scope:TaskResponse)
  })
_sym_db.RegisterMessage(TaskResponse)

IdVersionPair = _reflection.GeneratedProtocolMessageType('IdVersionPair', (_message.Message,), {
  'DESCRIPTOR' : _IDVERSIONPAIR,
  '__module__' : 'TaskServiceApi_pb2'
  # @@protoc_insertion_point(class_scope:IdVersionPair)
  })
_sym_db.RegisterMessage(IdVersionPair)

TaskInfo = _reflection.GeneratedProtocolMessageType('TaskInfo', (_message.Message,), {
  'DESCRIPTOR' : _TASKINFO,
  '__module__' : 'TaskServiceApi_pb2'
  # @@protoc_insertion_point(class_scope:TaskInfo)
  })
_sym_db.RegisterMessage(TaskInfo)


DESCRIPTOR._options = None

_TASKRPCSERVICE = _descriptor.ServiceDescriptor(
  name='TaskRpcService',
  full_name='TaskRpcService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=536,
  serialized_end=648,
  methods=[
  _descriptor.MethodDescriptor(
    name='getTaskInfoByName',
    full_name='TaskRpcService.getTaskInfoByName',
    index=0,
    containing_service=None,
    input_type=_NAMEREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getTaskInfoByID',
    full_name='TaskRpcService.getTaskInfoByID',
    index=1,
    containing_service=None,
    input_type=_IDREQUEST,
    output_type=_TASKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TASKRPCSERVICE)

DESCRIPTOR.services_by_name['TaskRpcService'] = _TASKRPCSERVICE

# @@protoc_insertion_point(module_scope)
