# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WorkflowServiceApi.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from entity import ScheduleJob_pb2 as entity_dot_ScheduleJob__pb2
from entity import UserInfo_pb2 as entity_dot_UserInfo__pb2
from entity import CommonResponse_pb2 as entity_dot_CommonResponse__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WorkflowServiceApi.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n com.ushareit.dstask.api.workflowB\022WorkflowServiceApi',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18WorkflowServiceApi.proto\x1a\x18\x65ntity/ScheduleJob.proto\x1a\x15\x65ntity/UserInfo.proto\x1a\x1b\x65ntity/CommonResponse.proto\"\xba\x01\n\rOnlineRequest\x12\x12\n\nworkflowId\x18\x01 \x01(\x05\x12\x14\n\x07version\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x1a\n\x04jobs\x18\x03 \x03(\x0b\x32\x0c.ScheduleJob\x12\x14\n\x0cworkflowName\x18\x04 \x01(\t\x12\x13\n\x0bgranularity\x18\x05 \x01(\t\x12\x0f\n\x07\x63rontab\x18\x06 \x01(\t\x12\x1b\n\x08userInfo\x18\x07 \x01(\x0b\x32\t.UserInfoB\n\n\x08_version\"A\n\x0eOfflineRequest\x12\x12\n\nworkflowId\x18\x01 \x01(\x05\x12\x1b\n\x08userInfo\x18\x02 \x01(\x0b\x32\t.UserInfo\"t\n\x10\x44\x65\x62ugTaskRequest\x12\x10\n\x08userName\x18\x01 \x01(\t\x12\x0e\n\x06\x63hatId\x18\x02 \x01(\t\x12!\n\x0bscheduleJob\x18\x03 \x03(\x0b\x32\x0c.ScheduleJob\x12\x1b\n\x08userInfo\x18\x04 \x01(\x0b\x32\t.UserInfo\"`\n\x0fStopTaskRequest\x12\x10\n\x08userName\x18\x01 \x01(\t\x12\x0e\n\x06\x63hatId\x18\x02 \x01(\t\x12\x0e\n\x06taskId\x18\x03 \x03(\x05\x12\x1b\n\x08userInfo\x18\x04 \x01(\x0b\x32\t.UserInfo\"H\n\x15\x44\x65leteWorkflowRequest\x12\x12\n\nworkflowId\x18\x01 \x01(\x05\x12\x1b\n\x08userInfo\x18\x02 \x01(\x0b\x32\t.UserInfo2\x91\x02\n\x12WorkflowRpcService\x12+\n\x06online\x12\x0e.OnlineRequest\x1a\x0f.CommonResponse\"\x00\x12-\n\x07offline\x12\x0f.OfflineRequest\x1a\x0f.CommonResponse\"\x00\x12\x31\n\tdebugTask\x12\x11.DebugTaskRequest\x1a\x0f.CommonResponse\"\x00\x12;\n\x0e\x64\x65leteWorkflow\x12\x16.DeleteWorkflowRequest\x1a\x0f.CommonResponse\"\x00\x12/\n\x08stopTask\x12\x10.StopTaskRequest\x1a\x0f.CommonResponse\"\x00\x42\x36\n com.ushareit.dstask.api.workflowB\x12WorkflowServiceApib\x06proto3'
  ,
  dependencies=[entity_dot_ScheduleJob__pb2.DESCRIPTOR,entity_dot_UserInfo__pb2.DESCRIPTOR,entity_dot_CommonResponse__pb2.DESCRIPTOR,])




_ONLINEREQUEST = _descriptor.Descriptor(
  name='OnlineRequest',
  full_name='OnlineRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='workflowId', full_name='OnlineRequest.workflowId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='OnlineRequest.version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='jobs', full_name='OnlineRequest.jobs', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='workflowName', full_name='OnlineRequest.workflowName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='granularity', full_name='OnlineRequest.granularity', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='crontab', full_name='OnlineRequest.crontab', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userInfo', full_name='OnlineRequest.userInfo', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_version', full_name='OnlineRequest._version',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=107,
  serialized_end=293,
)


_OFFLINEREQUEST = _descriptor.Descriptor(
  name='OfflineRequest',
  full_name='OfflineRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='workflowId', full_name='OfflineRequest.workflowId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userInfo', full_name='OfflineRequest.userInfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=295,
  serialized_end=360,
)


_DEBUGTASKREQUEST = _descriptor.Descriptor(
  name='DebugTaskRequest',
  full_name='DebugTaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userName', full_name='DebugTaskRequest.userName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chatId', full_name='DebugTaskRequest.chatId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scheduleJob', full_name='DebugTaskRequest.scheduleJob', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userInfo', full_name='DebugTaskRequest.userInfo', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=478,
)


_STOPTASKREQUEST = _descriptor.Descriptor(
  name='StopTaskRequest',
  full_name='StopTaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userName', full_name='StopTaskRequest.userName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chatId', full_name='StopTaskRequest.chatId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='taskId', full_name='StopTaskRequest.taskId', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userInfo', full_name='StopTaskRequest.userInfo', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=480,
  serialized_end=576,
)


_DELETEWORKFLOWREQUEST = _descriptor.Descriptor(
  name='DeleteWorkflowRequest',
  full_name='DeleteWorkflowRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='workflowId', full_name='DeleteWorkflowRequest.workflowId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userInfo', full_name='DeleteWorkflowRequest.userInfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=578,
  serialized_end=650,
)

_ONLINEREQUEST.fields_by_name['jobs'].message_type = entity_dot_ScheduleJob__pb2._SCHEDULEJOB
_ONLINEREQUEST.fields_by_name['userInfo'].message_type = entity_dot_UserInfo__pb2._USERINFO
_ONLINEREQUEST.oneofs_by_name['_version'].fields.append(
  _ONLINEREQUEST.fields_by_name['version'])
_ONLINEREQUEST.fields_by_name['version'].containing_oneof = _ONLINEREQUEST.oneofs_by_name['_version']
_OFFLINEREQUEST.fields_by_name['userInfo'].message_type = entity_dot_UserInfo__pb2._USERINFO
_DEBUGTASKREQUEST.fields_by_name['scheduleJob'].message_type = entity_dot_ScheduleJob__pb2._SCHEDULEJOB
_DEBUGTASKREQUEST.fields_by_name['userInfo'].message_type = entity_dot_UserInfo__pb2._USERINFO
_STOPTASKREQUEST.fields_by_name['userInfo'].message_type = entity_dot_UserInfo__pb2._USERINFO
_DELETEWORKFLOWREQUEST.fields_by_name['userInfo'].message_type = entity_dot_UserInfo__pb2._USERINFO
DESCRIPTOR.message_types_by_name['OnlineRequest'] = _ONLINEREQUEST
DESCRIPTOR.message_types_by_name['OfflineRequest'] = _OFFLINEREQUEST
DESCRIPTOR.message_types_by_name['DebugTaskRequest'] = _DEBUGTASKREQUEST
DESCRIPTOR.message_types_by_name['StopTaskRequest'] = _STOPTASKREQUEST
DESCRIPTOR.message_types_by_name['DeleteWorkflowRequest'] = _DELETEWORKFLOWREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OnlineRequest = _reflection.GeneratedProtocolMessageType('OnlineRequest', (_message.Message,), {
  'DESCRIPTOR' : _ONLINEREQUEST,
  '__module__' : 'WorkflowServiceApi_pb2'
  # @@protoc_insertion_point(class_scope:OnlineRequest)
  })
_sym_db.RegisterMessage(OnlineRequest)

OfflineRequest = _reflection.GeneratedProtocolMessageType('OfflineRequest', (_message.Message,), {
  'DESCRIPTOR' : _OFFLINEREQUEST,
  '__module__' : 'WorkflowServiceApi_pb2'
  # @@protoc_insertion_point(class_scope:OfflineRequest)
  })
_sym_db.RegisterMessage(OfflineRequest)

DebugTaskRequest = _reflection.GeneratedProtocolMessageType('DebugTaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _DEBUGTASKREQUEST,
  '__module__' : 'WorkflowServiceApi_pb2'
  # @@protoc_insertion_point(class_scope:DebugTaskRequest)
  })
_sym_db.RegisterMessage(DebugTaskRequest)

StopTaskRequest = _reflection.GeneratedProtocolMessageType('StopTaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOPTASKREQUEST,
  '__module__' : 'WorkflowServiceApi_pb2'
  # @@protoc_insertion_point(class_scope:StopTaskRequest)
  })
_sym_db.RegisterMessage(StopTaskRequest)

DeleteWorkflowRequest = _reflection.GeneratedProtocolMessageType('DeleteWorkflowRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEWORKFLOWREQUEST,
  '__module__' : 'WorkflowServiceApi_pb2'
  # @@protoc_insertion_point(class_scope:DeleteWorkflowRequest)
  })
_sym_db.RegisterMessage(DeleteWorkflowRequest)


DESCRIPTOR._options = None

_WORKFLOWRPCSERVICE = _descriptor.ServiceDescriptor(
  name='WorkflowRpcService',
  full_name='WorkflowRpcService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=653,
  serialized_end=926,
  methods=[
  _descriptor.MethodDescriptor(
    name='online',
    full_name='WorkflowRpcService.online',
    index=0,
    containing_service=None,
    input_type=_ONLINEREQUEST,
    output_type=entity_dot_CommonResponse__pb2._COMMONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='offline',
    full_name='WorkflowRpcService.offline',
    index=1,
    containing_service=None,
    input_type=_OFFLINEREQUEST,
    output_type=entity_dot_CommonResponse__pb2._COMMONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='debugTask',
    full_name='WorkflowRpcService.debugTask',
    index=2,
    containing_service=None,
    input_type=_DEBUGTASKREQUEST,
    output_type=entity_dot_CommonResponse__pb2._COMMONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='deleteWorkflow',
    full_name='WorkflowRpcService.deleteWorkflow',
    index=3,
    containing_service=None,
    input_type=_DELETEWORKFLOWREQUEST,
    output_type=entity_dot_CommonResponse__pb2._COMMONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='stopTask',
    full_name='WorkflowRpcService.stopTask',
    index=4,
    containing_service=None,
    input_type=_STOPTASKREQUEST,
    output_type=entity_dot_CommonResponse__pb2._COMMONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WORKFLOWRPCSERVICE)

DESCRIPTOR.services_by_name['WorkflowRpcService'] = _WORKFLOWRPCSERVICE

# @@protoc_insertion_point(module_scope)
