# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
FROM ubuntu:16.04

# install deps
RUN apt-get update -y && apt-get install -y \
        wget \
        python-dev \
        python-pip \
        libczmq-dev \
        libcurlpp-dev \
        libsasl2-dev \
        libldap2-dev \
        curl \
        libssl-dev \
        git \
        inetutils-telnet \
        bind9utils \
        zip \
        python-mysqldb \
        vim \
        unzip \
    && apt-get clean


RUN ln -s /usr/local/n/versions/node/10.16.0/bin/node /usr/bin/node -f

RUN pip install --upgrade pip

# Since we install vanilla Airflow, we also want to have support for Postgres and Kubernetes
RUN pip install -U setuptools && \
    pip install kubernetes==9.0.0 && \
    pip install cryptography && \
    pip install ldap3==2.5.1 && \
    pip install python-ldap==3.1.0 && \
    pip install psycopg2-binary==2.7.4  # I had issues with older versions of psycopg2, just a warning

# install airflow
ADD airflow.tar.gz /tmp/
COPY requirements.txt /tmp/requirements.txt
COPY compile.sh /tmp/compile.sh
RUN bash /tmp/compile.sh \
    && pip install --no-use-pep517 /tmp/airflow-source \
    && pip install -r /tmp/requirements.txt \

# install tini
ENV TINI_VERSION v0.18.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

# COPY airflow-test-env-init.sh /tmp/airflow-test-env-init.sh

# COPY bootstrap.sh /bootstrap.sh
# RUN chmod +x /bootstrap.sh

# ENTRYPOINT ["/bootstrap.sh"]
