# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
FROM centos:centos7

# install deps
# Since we install vanilla Airflow, we also want to have support for Postgres and Kubernetes
RUN yum groupinstall -y "Development tools" && \
    yum install -y openldap-devel python-devel && \
    yum install -y epel-release && \
    yum install -y python-pip && \
    yum install -y mysql-devel python-devel python-setuptools && \
    pip install --upgrade pip && \
    pip install -U setuptools && \
    rm -f /usr/lib/python2.7/site-packages/ipaddress* && \
    pip install kubernetes==9.0.0 && \
    pip install cryptography && \
    pip install ldap3==2.5.1 && \
    pip install python-ldap==3.1.0 && \
    pip install psycopg2-binary==2.7.4  # I had issues with older versions of psycopg2, just a warning

# install airflow
ADD airflow.tar.gz /tmp/
COPY requirements.txt /tmp/requirements.txt
COPY requirements_shareit.txt /tmp/requirements_shareit.txt
COPY compile.sh /tmp/compile.sh
RUN bash /tmp/compile.sh \
    && pip install -r /tmp/requirements.txt \
    && pip install -r /tmp/requirements_shareit.txt -i https://nexus.ushareit.me/repository/pypi-group/simple \
    && pip install --no-use-pep517 /tmp/airflow-source \
    && pip uninstall -y dataclasses

# install tini
ENV TINI_VERSION v0.18.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

ENV LC_ALL en_US.UTF-8
ENV LC_CTYPE en_US.UTF-8
ENV AIRFLOW_HOME /work/airflow/

# clean up unuse file to shrink image
